/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_information_system;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static student_information_system.Admin.myConnection;
import static student_information_system.Admin.okcancel;

/**
 *
 * @author INKILU
 */
public class term3 extends javax.swing.JFrame {

    /**
     * Creates new form term3
     */
    public term3() {
        initComponents();
        setTerm3Marks();
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.setRowHeight(25);
    }

    
       private void setTerm3Marks(){

    Connection con = myConnection();

       try{

PreparedStatement prest;

String sql ="select student_info.sid,name,eng_t3,sci_t3,ss_t3,math_t3,mal_t3,gtotal from marks,student_info where marks.sid = student_info.sid;";

prest= con.prepareStatement(sql);

ResultSet rs = prest.executeQuery(sql);

while(rs.next()){

   String mid  = String.valueOf(rs.getInt("sid"));
   String nm = rs.getString("name");
   String engt3 = rs.getString("eng_t3");
   String scit3= rs.getString("sci_t3");
   String sst3 = rs.getString("ss_t3");
   String matht3 = rs.getString("math_t3");
   String malt3 = rs.getString("mal_t3");
   String grdt3 = rs.getString("gtotal");

            String tbData[]={mid,nm,engt3,scit3,sst3,matht3,malt3,grdt3};

            DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();

            tblModel.addRow(tbData);

       }

       }catch (SQLException ex) {

            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);

        }

}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STU_ID", "NAME", "ENG", "SCI", "SS", "MATHS", "MAL", "TOTAL MARKS"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 780, 250));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102,130));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER MARKS");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ENG");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SCI");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SS");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MATHS");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MAL");

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("VIEW FINAL RESULT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(140, 140, 140)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 780, 160));

        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_information_system/term3back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int id;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                              
     Connection con = myConnection();

        if(id !=0){

           String eng= jTextField1.getText();
           String sci= jTextField2.getText();
           String ss= jTextField3.getText();
           String maths= jTextField4.getText();
           String mal= jTextField5.getText();
        //   String novval= jTextField12.getText();
        if( Integer.parseInt(eng)>100||Integer.parseInt(sci)>100||Integer.parseInt(ss)>100
            ||Integer.parseInt(maths)>100||Integer.parseInt(mal)>100){
          okcancel("Max mark is 100!");
          }
          else{
try{
    int total1 = Integer.parseInt(eng)+Integer.parseInt(sci)+Integer.parseInt(ss)+Integer.parseInt(maths)+Integer.parseInt(mal);
   String sql ="";  
   PreparedStatement prest;
        sql="update marks set eng_t3='"+eng+"',sci_t3='"+sci+"',ss_t3='"+ss+"',math_t3='"+maths+"',mal_t3='"+mal+"',gtotal='"+total1+"'where sid='"+id+"'";

  prest= con.prepareStatement(sql);

 prest.execute(sql);

  dispose();
term3 a = new term3();
 a.show();
 con.close();

id =0;

} catch (SQLException ex) {
 Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
 }

        }    
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
  System.out.println(id);
 Connection con = myConnection();

try{

PreparedStatement prest;

String sql ="select eng_t3,sci_t3,ss_t3,math_t3,mal_t3,gtotal from marks where sid="+id;

prest= con.prepareStatement(sql);

ResultSet rs = prest.executeQuery(sql);// PreparedStatement object’s executeQuery () method is called to execute the SQL SELECT statement, returning a ResultSet into rs.

while(rs.next()){

    jTextField1.setText(rs.getString("eng_t3"));// Retrieves value of the second column in the current row, which is the username field

    jTextField2.setText(rs.getString("sci_t3"));

    jTextField3.setText(rs.getString("ss_t3"));

    jTextField4.setText(rs.getString("math_t3"));
    
    jTextField5.setText(rs.getString("mal_t3"));

}

 rs.close();

 prest.close();

   

}       catch (SQLException ex) {

            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          dispose();
Admin a = new Admin();
 a.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// database
 Connection con = myConnection();
       try{
PreparedStatement prest,prest2;
String sql2="select * from attendance where sid="+id;
prest2=con.prepareStatement(sql2);
ResultSet rr = prest2.executeQuery(sql2);
float attsum=0;
while(rr.next()){
attsum=Float.parseFloat(rr.getString("jun"))+Float.parseFloat(rr.getString("jul"))+Float.parseFloat(rr.getString("aug"))+Float.parseFloat(rr.getString("sept"))
+Float.parseFloat(rr.getString("oct"))+Float.parseFloat(rr.getString("nov"))+Float.parseFloat(rr.getString("dece"))+Float.parseFloat(rr.getString("jan"))
+Float.parseFloat(rr.getString("feb"))+Float.parseFloat(rr.getString("mar"));
}
float attper = (attsum/230)*100;
double roundOff = (double) Math.round(attper * 100) / 100;
System.out.println("Sum is "+roundOff);
String sql ="select sid,name,class,eng_t3,sci_t3,ss_t3,math_t3,mal_t3,gtotal from student_info natural join marks where sid="+id;
prest= con.prepareStatement(sql);
ResultSet rs = prest.executeQuery(sql);
while(rs.next()){
float sumper = Float.parseFloat(rs.getString("gtotal"));
float resull = (sumper/500)*100;
System.out.println(rs.getString("sid")+rs.getString("name")+rs.getString("class"));
System.out.println(resull);
    try{
        String file_name="D:\\out\\output.pdf";
        Document document = new Document();
        PdfWriter.getInstance(document,new FileOutputStream(file_name));
        System.out.println(id);
        document.open();
        // Add paragraph
         Paragraph heading = new Paragraph(new Phrase(1,"Progress Card\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n--------",FontFactory.getFont(FontFactory.COURIER,24)));
         Paragraph detailspdf = new Paragraph("Roll No: "+rs.getString("sid")+"\n"+"Name: "+rs.getString("name")+"\n"+"Class: "+rs.getString("class"));
         Paragraph div = new Paragraph("\n\n");
         Paragraph markspdf = new Paragraph(new Phrase(1,"Marks(Final)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n--------",FontFactory.getFont(FontFactory.COURIER,18)));
         document.add(heading);
         document.add(detailspdf);
         document.add(div);
         document.add(markspdf);
         document.add(div);
         // ADD A TABLE
         PdfPTable table = new PdfPTable(6);
         PdfPCell c1 = new PdfPCell(new Phrase("English"));
         table.addCell(c1);
         c1 = new PdfPCell(new Phrase("Science"));
         table.addCell(c1);
         c1 = new PdfPCell(new Phrase("SS"));
         table.addCell(c1);
         c1 = new PdfPCell(new Phrase("Maths"));
         table.addCell(c1);
         c1 = new PdfPCell(new Phrase("Mal"));
         table.addCell(c1);
         c1 = new PdfPCell(new Phrase("Total"));
         table.addCell(c1);
         table.setHeaderRows(1);
         table.addCell(rs.getString("eng_t3"));
         table.addCell(rs.getString("sci_t3"));
         table.addCell(rs.getString("ss_t3"));
         table.addCell(rs.getString("math_t3"));
         table.addCell(rs.getString("mal_t3"));
         table.addCell(rs.getString("gtotal"));
         document.add(table);
         // table end
        Paragraph markper = new Paragraph("Mark % : "+resull);
        Paragraph attenper = new Paragraph("Attendance % : "+roundOff);
        document.add(div);
        document.add(markper);
        document.add(attenper);
        if(resull>=50 && roundOff >=50){
        Paragraph passorfail = new Paragraph("Is Eligible for Higher Studies");
        document.add(passorfail);
        }else{
        Paragraph passorfail = new Paragraph("Is Not Eligible for Higher Studies");
        document.add(passorfail);
        }
        document.close();
     } catch (Exception e){
     System.out.println(e);
     }
       }// resultset 2 closing
       }catch (SQLException ex) {

            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);

        }      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(term3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(term3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(term3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(term3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new term3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
